### ISSUE TITLE
support for ROS2 

### ISSUE THREAD

**Issue by addy1997** [yayaneath/GeoGrasp#10]
Hi @yayaneath,

Referring to the previous issue (#9), I have changed the code for ROS2. These are some changes. The fork can be found [here](https://github.com/addy1997/GeoGrasp/tree/addy1997-patch-ros2)

1. cloud_processor.cpp file is changed
2. CMakeLists.txt
3. package.xml

I want someone to try and test the build. Can that be done?

**Comment by yayaneath** [comment]
Hi @addy1997 

I can do that but I won't have the time until next week. Let me know if you manage to check the changes in the meantime.

**Comment by addy1997** [comment]
> Hi @addy1997
> 
> I can do that but I won't have the time until next week. Let me know if you manage to check the changes in the meantime.

No problem, If I am able to do it, I will add the documentation and update the readme of my fork. Hope you are okay with that?

**Comment by yayaneath** [comment]
That's completely ok!

**Comment by addy1997** [comment]
@yayaneath, I couldn't manage to test run the changes in Geograsp. My apologies. For now, I will close the issue. The fork remains intact. Thanks
