### ISSUE TITLE
getting the object point cloud in different position than the actual input point cloud

### ISSUE THREAD

**Issue by mohammad200h** [yayaneath/GeoGrasp#2]
Hey I am trying to reimplement your work and I am getting the object point cloud to be in different position than input cloud. 
gazebo:
<img width="575" alt="Screenshot 2019-09-12 04 58 06" src="https://user-images.githubusercontent.com/21280923/64753128-fd2d1680-d519-11e9-86c6-a0abf2b11f91.png">
Moveit:
with two point cloud before and after processing:
<img width="817" alt="Screenshot 2019-09-12 04 57 42" src="https://user-images.githubusercontent.com/21280923/64753163-1fbf2f80-d51a-11e9-89d8-98b76dc78c2e.png">
The issue seems to be the moment ros point cloud is converted to PCL is loses frame of reference
this can be seen in the following picture.
<img width="806" alt="Screenshot 2019-09-12 05 37 52" src="https://user-images.githubusercontent.com/21280923/64754569-bf32f100-d51f-11e9-996d-ae56605f42cd.png">

Do you know how to solve this issue. I have tried bunch of camera configuration and also the one suggested in the paper but it seems not to work.

Thanks 
Mohammad

**Comment by yayaneath** [comment]
Hello Mohammad,

sorry for the late reply! My guess is that the point cloud being published afterwards is in a reference system which is not being properly converted to your 'world' frame in your visualization.

GeoGrasp does not provide any code for publishing the processed point cloud, so I think the problem you are experiencing is there.
